name: build-wheels

on:
  pull_request:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CIBW_ARCHS: auto64
  CIBW_BUILD: "cp313-*"
  CIBW_BUILD_VERBOSITY: 2

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
    name: ${{ matrix.os }} / ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        env:
          CIBW_BUILD: "cp313-manylinux*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_ALL: |
            cat /etc/os-release
            dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
            dnf update -y
            dnf install -y vulkan-devel libuuid-devel libXinerama-devel libXcursor-devel libXi-devel libXrandr-devel libxkbcommon-devel wayland-devel zlib-devel patchelf
          CIBW_REPAIR_WHEEL_COMMAND: >-
            auditwheel show {wheel} && auditwheel repair -w {dest_dir} {wheel}
            --exclude libvulkan.so.1
            --exclude libluisa-core.so
            --exclude libluisa-ast.so
            --exclude libluisa-dsl.so
            --exclude libluisa-runtime.so
            --exclude libluisa-xir.so
            --exclude libluisa-osl.so
            --exclude libluisa-backend-vulkan.so
            --exclude libluisa-validation-layer.so
          CMAKE_ARGS: >-
            -D LUISA_COMPUTE_ENABLE_CUDA=OFF
            -D LUISA_COMPUTE_ENABLE_VULKAN=ON
            -D LUISA_COMPUTE_ENABLE_METAL=OFF
            -D LUISA_COMPUTE_ENABLE_DX=OFF
            -D LUISA_COMPUTE_ENABLE_FALLBACK=OFF
        run: |
          python -m pip install -U cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [15]
    name: macos-${{ matrix.os }}
    runs-on: macos-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup LLVM
        run: |
          brew install --overwrite python@3.12
          brew install --overwrite llvm molten-vk

      - name: Build wheels
        run: |
          export CC=/opt/homebrew/opt/llvm/bin/clang
          export CXX=/opt/homebrew/opt/llvm/bin/clang++
          export CMAKE_ARGS="-D LUISA_COMPUTE_ENABLE_CUDA=OFF -D LUISA_COMPUTE_ENABLE_VULKAN=OFF -D LUISA_COMPUTE_ENABLE_METAL=ON -D LUISA_COMPUTE_ENABLE_DX=OFF -D LUISA_COMPUTE_ENABLE_FALLBACK=OFF"
          python3 -m pip install -U cibuildwheel --break-system-packages
          export MACOSX_DEPLOYMENT_TARGET=${{ matrix.os }}.0
          python3 -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macOS-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build-windows:
    name: windows-2025
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4

      - name: Setup Vulkan SDK
        uses: johnnynunez/setup-vulkan-sdk@v1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build wheels
        shell: cmd
        env:
          CMAKE_ARGS: >-
            -D LUISA_COMPUTE_ENABLE_CUDA=OFF
            -D LUISA_COMPUTE_ENABLE_VULKAN=ON
            -D LUISA_COMPUTE_ENABLE_DX=OFF
            -D LUISA_COMPUTE_ENABLE_METAL=OFF
            -D LUISA_COMPUTE_ENABLE_FALLBACK=OFF
        run: |
          python -m pip install -U cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows
          path: ./wheelhouse/*.whl

  release-whl:
    name: release-whl
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build-linux
      - build-macos
      - build-windows
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Upload release wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-whl
          path: dist/*.whl

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
